version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hackaton_db
    restart: always
    environment:
      POSTGRES_DB: hackaton_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /Users/gmailgozzo/WebstormProjects/Bartrack/data:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hackaton_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
