# Generated by Django 5.2.7 on 2025-10-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoosballTable',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In use'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('condition_state', models.CharField(max_length=50)),
            ],
        ),
    ]
