# Generated by Django 5.2.7 on 2025-10-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foosball_tables', '0002_rename_id_foosballtable_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foosballtable',
            old_name='location',
            new_name='name',
        ),
    ]
