# Generated by Django 5.2.7 on 2025-10-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue')], max_length=10)),
                ('role', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense')], max_length=10)),
                ('is_substitute', models.BooleanField(default=False)),
                ('goals', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('save', models.IntegerField(default=0)),
                ('possession_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='players.player')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
