# Generated by Django 5.2.7 on 2025-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='is_substitute',
        ),
        migrations.AddField(
            model_name='performance',
            name='substitute',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_at',
            field=models.CharField(default='00:00:00', max_length=128),
        ),
    ]
