# Generated by Django 5.2.7 on 2025-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_remove_performance_is_substitute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='substitute',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default='no', max_length=10),
        ),
    ]
