# Generated by Django 5.2.7 on 2025-10-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_music'),
        ('performances', '0004_rename_game_performance_game_id_and_more'),
        ('players', '0007_alter_player_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('game', 'player')},
        ),
    ]
