# Generated by Django 5.2.7 on 2025-10-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_rename_game_id_performance_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='possession_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
