# Generated by Django 5.2.7 on 2025-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_alter_performance_possession_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='substitute',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default='no', max_length=10, null=True),
        ),
    ]
