# Generated by Django 5.2.7 on 2025-10-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_date_inscription_player_email_player_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='id',
            new_name='player_id',
        ),
    ]
