# Generated by Django 5.2.7 on 2025-10-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_id_player_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='id',
        ),
    ]
