# Generated by Django 5.2.7 on 2025-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_rename_player_id_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
