# Generated by Django 5.2.7 on 2025-10-17 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foosball_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('game_date', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('score_red', models.IntegerField(default=0)),
                ('score_blue', models.IntegerField(default=0)),
                ('winner_team', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('ball_type', models.CharField(blank=True, max_length=20)),
                ('music', models.CharField(blank=True, max_length=50)),
                ('referent', models.CharField(blank=True, max_length=20)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='foosball_tables.foosballtable')),
            ],
        ),
    ]
