# Generated by Django 5.2.7 on 2025-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
