# Generated by Django 5.2.7 on 2025-10-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='table',
            new_name='table_id',
        ),
    ]
