# Generated by Django 5.2.7 on 2025-10-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_table_game_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner_team',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue')], max_length=128),
        ),
    ]
