# Generated by Django 5.2.7 on 2025-10-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foosball_tables', '0003_rename_location_foosballtable_name'),
        ('games', '0004_alter_game_winner_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_game', to='foosball_tables.foosballtable'),
        ),
    ]
