# Generated by Django 5.2.7 on 2025-10-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='table_id',
            new_name='table',
        ),
    ]
