# Generated by Django 5.2.7 on 2025-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_rename_table_id_game_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ball_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
