# Generated by Django 5.2.7 on 2025-10-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_ball_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='referent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
